//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WSEncomiendaBD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEncomiendaBD.IBDService")]
    public interface IBDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/ListarDatos", ReplyAction="http://tempuri.org/IBDService/ListarDatosResponse")]
        BLL.WSEncomiendaBD.ListarDatosResponse ListarDatos(BLL.WSEncomiendaBD.ListarDatosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/ListarDatos", ReplyAction="http://tempuri.org/IBDService/ListarDatosResponse")]
        System.Threading.Tasks.Task<BLL.WSEncomiendaBD.ListarDatosResponse> ListarDatosAsync(BLL.WSEncomiendaBD.ListarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/FiltarDatos", ReplyAction="http://tempuri.org/IBDService/FiltarDatosResponse")]
        BLL.WSEncomiendaBD.FiltarDatosResponse FiltarDatos(BLL.WSEncomiendaBD.FiltarDatosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/FiltarDatos", ReplyAction="http://tempuri.org/IBDService/FiltarDatosResponse")]
        System.Threading.Tasks.Task<BLL.WSEncomiendaBD.FiltarDatosResponse> FiltarDatosAsync(BLL.WSEncomiendaBD.FiltarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/InsertarDato", ReplyAction="http://tempuri.org/IBDService/InsertarDatoResponse")]
        BLL.WSEncomiendaBD.InsertarDatoResponse InsertarDato(BLL.WSEncomiendaBD.InsertarDatoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/InsertarDato", ReplyAction="http://tempuri.org/IBDService/InsertarDatoResponse")]
        System.Threading.Tasks.Task<BLL.WSEncomiendaBD.InsertarDatoResponse> InsertarDatoAsync(BLL.WSEncomiendaBD.InsertarDatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/ModificarDato", ReplyAction="http://tempuri.org/IBDService/ModificarDatoResponse")]
        BLL.WSEncomiendaBD.ModificarDatoResponse ModificarDato(BLL.WSEncomiendaBD.ModificarDatoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/ModificarDato", ReplyAction="http://tempuri.org/IBDService/ModificarDatoResponse")]
        System.Threading.Tasks.Task<BLL.WSEncomiendaBD.ModificarDatoResponse> ModificarDatoAsync(BLL.WSEncomiendaBD.ModificarDatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/EliminarDato", ReplyAction="http://tempuri.org/IBDService/EliminarDatoResponse")]
        BLL.WSEncomiendaBD.EliminarDatoResponse EliminarDato(BLL.WSEncomiendaBD.EliminarDatoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBDService/EliminarDato", ReplyAction="http://tempuri.org/IBDService/EliminarDatoResponse")]
        System.Threading.Tasks.Task<BLL.WSEncomiendaBD.EliminarDatoResponse> EliminarDatoAsync(BLL.WSEncomiendaBD.EliminarDatoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreTabla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public ListarDatosRequest() {
        }
        
        public ListarDatosRequest(string sNombreSP, string sNombreTabla, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sNombreTabla = sNombreTabla;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosResponse() {
        }
        
        public ListarDatosResponse(System.Data.DataTable ListarDatosResult, string sMsjError) {
            this.ListarDatosResult = ListarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreTabla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sNombreParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sTipoParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sValorParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string sMsjError;
        
        public FiltarDatosRequest() {
        }
        
        public FiltarDatosRequest(string sNombreSP, string sNombreTabla, string sNombreParametro, string sTipoParametro, string sValorParametro, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sNombreTabla = sNombreTabla;
            this.sNombreParametro = sNombreParametro;
            this.sTipoParametro = sTipoParametro;
            this.sValorParametro = sValorParametro;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable FiltarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public FiltarDatosResponse() {
        }
        
        public FiltarDatosResponse(System.Data.DataTable FiltarDatosResult, string sMsjError) {
            this.FiltarDatosResult = FiltarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarDato", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertarDatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreTabla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public char cAccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sMsjError;
        
        public InsertarDatoRequest() {
        }
        
        public InsertarDatoRequest(string sNombreSP, string sNombreTabla, System.Data.DataTable dtParametros, char cAccion, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sNombreTabla = sNombreTabla;
            this.dtParametros = dtParametros;
            this.cAccion = cAccion;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarDatoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertarDatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertarDatoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public char cAccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public InsertarDatoResponse() {
        }
        
        public InsertarDatoResponse(string InsertarDatoResult, char cAccion, string sMsjError) {
            this.InsertarDatoResult = InsertarDatoResult;
            this.cAccion = cAccion;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarDato", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModificarDatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreTabla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public char cAccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sMsjError;
        
        public ModificarDatoRequest() {
        }
        
        public ModificarDatoRequest(string sNombreSP, string sNombreTabla, System.Data.DataTable dtParametros, char cAccion, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sNombreTabla = sNombreTabla;
            this.dtParametros = dtParametros;
            this.cAccion = cAccion;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarDatoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ModificarDatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public char cAccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ModificarDatoResponse() {
        }
        
        public ModificarDatoResponse(char cAccion, string sMsjError) {
            this.cAccion = cAccion;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarDato", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EliminarDatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreTabla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sNombreParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sTipoParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sValorParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string sMsjError;
        
        public EliminarDatoRequest() {
        }
        
        public EliminarDatoRequest(string sNombreSP, string sNombreTabla, string sNombreParametro, string sTipoParametro, string sValorParametro, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sNombreTabla = sNombreTabla;
            this.sNombreParametro = sNombreParametro;
            this.sTipoParametro = sTipoParametro;
            this.sValorParametro = sValorParametro;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarDatoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EliminarDatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sMsjError;
        
        public EliminarDatoResponse() {
        }
        
        public EliminarDatoResponse(string sMsjError) {
            this.sMsjError = sMsjError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBDServiceChannel : BLL.WSEncomiendaBD.IBDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDServiceClient : System.ServiceModel.ClientBase<BLL.WSEncomiendaBD.IBDService>, BLL.WSEncomiendaBD.IBDService {
        
        public BDServiceClient() {
        }
        
        public BDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSEncomiendaBD.ListarDatosResponse BLL.WSEncomiendaBD.IBDService.ListarDatos(BLL.WSEncomiendaBD.ListarDatosRequest request) {
            return base.Channel.ListarDatos(request);
        }
        
        public System.Data.DataTable ListarDatos(string sNombreSP, string sNombreTabla, ref string sMsjError) {
            BLL.WSEncomiendaBD.ListarDatosRequest inValue = new BLL.WSEncomiendaBD.ListarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreTabla = sNombreTabla;
            inValue.sMsjError = sMsjError;
            BLL.WSEncomiendaBD.ListarDatosResponse retVal = ((BLL.WSEncomiendaBD.IBDService)(this)).ListarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.ListarDatosResult;
        }
        
        public System.Threading.Tasks.Task<BLL.WSEncomiendaBD.ListarDatosResponse> ListarDatosAsync(BLL.WSEncomiendaBD.ListarDatosRequest request) {
            return base.Channel.ListarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSEncomiendaBD.FiltarDatosResponse BLL.WSEncomiendaBD.IBDService.FiltarDatos(BLL.WSEncomiendaBD.FiltarDatosRequest request) {
            return base.Channel.FiltarDatos(request);
        }
        
        public System.Data.DataTable FiltarDatos(string sNombreSP, string sNombreTabla, string sNombreParametro, string sTipoParametro, string sValorParametro, ref string sMsjError) {
            BLL.WSEncomiendaBD.FiltarDatosRequest inValue = new BLL.WSEncomiendaBD.FiltarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreTabla = sNombreTabla;
            inValue.sNombreParametro = sNombreParametro;
            inValue.sTipoParametro = sTipoParametro;
            inValue.sValorParametro = sValorParametro;
            inValue.sMsjError = sMsjError;
            BLL.WSEncomiendaBD.FiltarDatosResponse retVal = ((BLL.WSEncomiendaBD.IBDService)(this)).FiltarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.FiltarDatosResult;
        }
        
        public System.Threading.Tasks.Task<BLL.WSEncomiendaBD.FiltarDatosResponse> FiltarDatosAsync(BLL.WSEncomiendaBD.FiltarDatosRequest request) {
            return base.Channel.FiltarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSEncomiendaBD.InsertarDatoResponse BLL.WSEncomiendaBD.IBDService.InsertarDato(BLL.WSEncomiendaBD.InsertarDatoRequest request) {
            return base.Channel.InsertarDato(request);
        }
        
        public string InsertarDato(string sNombreSP, string sNombreTabla, System.Data.DataTable dtParametros, ref char cAccion, ref string sMsjError) {
            BLL.WSEncomiendaBD.InsertarDatoRequest inValue = new BLL.WSEncomiendaBD.InsertarDatoRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreTabla = sNombreTabla;
            inValue.dtParametros = dtParametros;
            inValue.cAccion = cAccion;
            inValue.sMsjError = sMsjError;
            BLL.WSEncomiendaBD.InsertarDatoResponse retVal = ((BLL.WSEncomiendaBD.IBDService)(this)).InsertarDato(inValue);
            cAccion = retVal.cAccion;
            sMsjError = retVal.sMsjError;
            return retVal.InsertarDatoResult;
        }
        
        public System.Threading.Tasks.Task<BLL.WSEncomiendaBD.InsertarDatoResponse> InsertarDatoAsync(BLL.WSEncomiendaBD.InsertarDatoRequest request) {
            return base.Channel.InsertarDatoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSEncomiendaBD.ModificarDatoResponse BLL.WSEncomiendaBD.IBDService.ModificarDato(BLL.WSEncomiendaBD.ModificarDatoRequest request) {
            return base.Channel.ModificarDato(request);
        }
        
        public void ModificarDato(string sNombreSP, string sNombreTabla, System.Data.DataTable dtParametros, ref char cAccion, ref string sMsjError) {
            BLL.WSEncomiendaBD.ModificarDatoRequest inValue = new BLL.WSEncomiendaBD.ModificarDatoRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreTabla = sNombreTabla;
            inValue.dtParametros = dtParametros;
            inValue.cAccion = cAccion;
            inValue.sMsjError = sMsjError;
            BLL.WSEncomiendaBD.ModificarDatoResponse retVal = ((BLL.WSEncomiendaBD.IBDService)(this)).ModificarDato(inValue);
            cAccion = retVal.cAccion;
            sMsjError = retVal.sMsjError;
        }
        
        public System.Threading.Tasks.Task<BLL.WSEncomiendaBD.ModificarDatoResponse> ModificarDatoAsync(BLL.WSEncomiendaBD.ModificarDatoRequest request) {
            return base.Channel.ModificarDatoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSEncomiendaBD.EliminarDatoResponse BLL.WSEncomiendaBD.IBDService.EliminarDato(BLL.WSEncomiendaBD.EliminarDatoRequest request) {
            return base.Channel.EliminarDato(request);
        }
        
        public void EliminarDato(string sNombreSP, string sNombreTabla, string sNombreParametro, string sTipoParametro, string sValorParametro, ref string sMsjError) {
            BLL.WSEncomiendaBD.EliminarDatoRequest inValue = new BLL.WSEncomiendaBD.EliminarDatoRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreTabla = sNombreTabla;
            inValue.sNombreParametro = sNombreParametro;
            inValue.sTipoParametro = sTipoParametro;
            inValue.sValorParametro = sValorParametro;
            inValue.sMsjError = sMsjError;
            BLL.WSEncomiendaBD.EliminarDatoResponse retVal = ((BLL.WSEncomiendaBD.IBDService)(this)).EliminarDato(inValue);
            sMsjError = retVal.sMsjError;
        }
        
        public System.Threading.Tasks.Task<BLL.WSEncomiendaBD.EliminarDatoResponse> EliminarDatoAsync(BLL.WSEncomiendaBD.EliminarDatoRequest request) {
            return base.Channel.EliminarDatoAsync(request);
        }
    }
}
